### ISSUE TITLE
object-curly-newline と prettierのルールが衝突している

### ISSUE THREAD

**Issue by tosuke** [togetter/eslint-config-togetter#1]
[eslint-config-airbnb-baseにおけるobject-curly-newlineの設定](https://github.com/airbnb/javascript/blob/ab72ab9e90f403e90590f8815e0563248af10470/packages/eslint-config-airbnb-base/rules/style.js#L396-401) とprettierのフォーマットが衝突することがあるようです。

**Comment by tosuke** [comment]
[eslint-config-prettierがオフにしている](https://github.com/prettier/eslint-config-prettier/blob/e0b66486a73676d7eaf59c206446def3b2b23d24/index.js#L62)ルールなのでオフにしたほうがよさそうです

**Comment by yositosi** [comment]
どっちが、いいんかなー。適切に改行してくれるのも良い気がするけど。

**Comment by yositosi** [comment]
`"object-curly-newline": "off",` で行きましょう

**Comment by yositosi** [comment]
というか、togetterの設定から消しましょう。

**Comment by neet** [comment]
[eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) はPrettierと競合する（~= Prettierの機能で補える）ESLintルールを全てオフにするconfigなので、Prettierが有効ならそれらの設定は不要です。 このリポジトリにもeslint-config-prettierを追加するのが良いと思います。

**Comment by tosuke** [comment]
https://github.com/togetter/eslint-config-togetter/blob/18726490d527b45cc70f581c124e86a68b03ad4b/index.js#L3 で `plugin/prettier:recommended`をextendしているのですが、ここでeslint-config-prettierの設定が適用されています。しかしtogetter独自の設定で上書きされた結果再び有効化されているようです。

**Comment by entyo** [comment]
@Tosuke ありがとうございます :pray:

> しかしtogetter独自の設定で上書きされた結果再び有効化されているようです

これは具体的にどの箇所の影響で上書き・再有効化されてしまっているのでしょうか？

**Comment by tosuke** [comment]
@entyo 
> これは具体的にどの箇所の影響で上書き・再有効化されてしまっているのでしょうか？

https://github.com/togetter/eslint-config-togetter/blob/18726490d527b45cc70f581c124e86a68b03ad4b/index.js#L21 ここですね。`"off"`になった設定が上書きされて`[1]`(warning)になってしまっています。

**Comment by yositosi** [comment]
Togetter独自の設定が、prettierとカニバっているなら、Togetterの設定は外していってもよい。
というか、全部外して、どうしても入れたいものだけ入れる感じでいいのでは？

関連
togetter側の対応
https://github.com/togetter/togetter/pull/4825
