### ISSUE TITLE
prettierを最後に追加したい

### ISSUE THREAD

**Issue by kazushisan** [togetter/eslint-config-togetter#3]
https://github.com/prettier/eslint-config-prettier/blame/master/README.md#L53-L55

このようにprettierを最後に指定しないといけなさそうなのですが 、`eslint-config-togetter` にprettierが入っていると`@typescript-eslint/parser`などを指定したいときに再度prettierを指定することになるので、できればprettierを `eslint-config-togetter` から消したいと思うのですがいかがでしょうか

```json
{
  "parser": "@typescript-eslint/parser",
  "extends": [
    "togetter",
    "plugin:jest/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint"
  ],
  "plugins": [
    "@typescript-eslint",
    "jest"
  ],
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [
          ".ts"
        ]
      }
    }
  }
}
```

**Comment by entyo** [comment]
@kazushisan 

> このようにprettierを最後に指定しないといけなさそうなのですが 

コレ知りませんでした、消したほうがいいと思いますありがとうございます :pray:

**Comment by entyo** [comment]
https://github.com/togetter/eslint-config-togetter/commit/c0884f859e007e42a098ccd96d5b5ce9e73b0157
